server:
  port: 8169

dconcurrent:
    hostList:
    serverport: 50052

spring:
  application:
      name: hbase-scan-inc
  http:
      encoding:
        enabled: true
        force: true
        charset: UTF-8
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://:3306/hbase_inc_source?useUnicode=true&characterEncoding=utf-8
      username: test
      password: test

mybatis:
  mapper-locations: classpath*:mappers/*
  configuration:
      mapUnderscoreToCamelCase: true

