// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: d-concurrent.proto

package util.dconcurrent.core;

/**
 * Protobuf type {@code dconcurrent.DStatus}
 */
public  final class DStatus extends
    com.google.protobuf.GeneratedMessage
    implements DStatusOrBuilder {
  // Use DStatus.newBuilder() to construct.
  private DStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
    this.unknownFields = builder.getUnknownFields();
  }
  private DStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

  private static final DStatus defaultInstance;
  public static DStatus getDefaultInstance() {
    return defaultInstance;
  }

  public DStatus getDefaultInstanceForType() {
    return defaultInstance;
  }

  private final com.google.protobuf.UnknownFieldSet unknownFields;
  @Override
  public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
    return this.unknownFields;
  }
  private DStatus(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    initFields();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            runCount_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            callCount_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e.getMessage()).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DStatus_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            util.dconcurrent.core.DStatus.class, util.dconcurrent.core.DStatus.Builder.class);
  }

  public static com.google.protobuf.Parser<DStatus> PARSER =
      new com.google.protobuf.AbstractParser<DStatus>() {
    public DStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DStatus(input, extensionRegistry);
    }
  };

  @Override
  public com.google.protobuf.Parser<DStatus> getParserForType() {
    return PARSER;
  }

  private int bitField0_;
  // optional int32 runCount = 1;
  public static final int RUNCOUNT_FIELD_NUMBER = 1;
  private int runCount_;
  /**
   * <code>optional int32 runCount = 1;</code>
   */
  public boolean hasRunCount() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional int32 runCount = 1;</code>
   */
  public int getRunCount() {
    return runCount_;
  }

  // optional int32 callCount = 2;
  public static final int CALLCOUNT_FIELD_NUMBER = 2;
  private int callCount_;
  /**
   * <code>optional int32 callCount = 2;</code>
   */
  public boolean hasCallCount() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional int32 callCount = 2;</code>
   */
  public int getCallCount() {
    return callCount_;
  }

  private void initFields() {
    runCount_ = 0;
    callCount_ = 0;
  }
  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized != -1) return isInitialized == 1;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt32(1, runCount_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      output.writeInt32(2, callCount_);
    }
    getUnknownFields().writeTo(output);
  }

  private int memoizedSerializedSize = -1;
  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, runCount_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, callCount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSerializedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  protected Object writeReplace()
      throws java.io.ObjectStreamException {
    return super.writeReplace();
  }

  public static util.dconcurrent.core.DStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static util.dconcurrent.core.DStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static util.dconcurrent.core.DStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static util.dconcurrent.core.DStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static util.dconcurrent.core.DStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static util.dconcurrent.core.DStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }
  public static util.dconcurrent.core.DStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input);
  }
  public static util.dconcurrent.core.DStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseDelimitedFrom(input, extensionRegistry);
  }
  public static util.dconcurrent.core.DStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return PARSER.parseFrom(input);
  }
  public static util.dconcurrent.core.DStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return PARSER.parseFrom(input, extensionRegistry);
  }

  public static Builder newBuilder() { return Builder.create(); }
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder(util.dconcurrent.core.DStatus prototype) {
    return newBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() { return newBuilder(this); }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code dconcurrent.DStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder>
     implements util.dconcurrent.core.DStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DStatus_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              util.dconcurrent.core.DStatus.class, util.dconcurrent.core.DStatus.Builder.class);
    }

    // Construct using util.dconcurrent.core.DStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
      }
    }
    private static Builder create() {
      return new Builder();
    }

    public Builder clear() {
      super.clear();
      runCount_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      callCount_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public Builder clone() {
      return create().mergeFrom(buildPartial());
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return util.dconcurrent.core.DConcurrent.internal_static_dconcurrent_DStatus_descriptor;
    }

    public util.dconcurrent.core.DStatus getDefaultInstanceForType() {
      return util.dconcurrent.core.DStatus.getDefaultInstance();
    }

    public util.dconcurrent.core.DStatus build() {
      util.dconcurrent.core.DStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public util.dconcurrent.core.DStatus buildPartial() {
      util.dconcurrent.core.DStatus result = new util.dconcurrent.core.DStatus(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.runCount_ = runCount_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.callCount_ = callCount_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof util.dconcurrent.core.DStatus) {
        return mergeFrom((util.dconcurrent.core.DStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(util.dconcurrent.core.DStatus other) {
      if (other == util.dconcurrent.core.DStatus.getDefaultInstance()) return this;
      if (other.hasRunCount()) {
        setRunCount(other.getRunCount());
      }
      if (other.hasCallCount()) {
        setCallCount(other.getCallCount());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      util.dconcurrent.core.DStatus parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (util.dconcurrent.core.DStatus) e.getUnfinishedMessage();
        throw e;
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    // optional int32 runCount = 1;
    private int runCount_ ;
    /**
     * <code>optional int32 runCount = 1;</code>
     */
    public boolean hasRunCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 runCount = 1;</code>
     */
    public int getRunCount() {
      return runCount_;
    }
    /**
     * <code>optional int32 runCount = 1;</code>
     */
    public Builder setRunCount(int value) {
      bitField0_ |= 0x00000001;
      runCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 runCount = 1;</code>
     */
    public Builder clearRunCount() {
      bitField0_ = (bitField0_ & ~0x00000001);
      runCount_ = 0;
      onChanged();
      return this;
    }

    // optional int32 callCount = 2;
    private int callCount_ ;
    /**
     * <code>optional int32 callCount = 2;</code>
     */
    public boolean hasCallCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 callCount = 2;</code>
     */
    public int getCallCount() {
      return callCount_;
    }
    /**
     * <code>optional int32 callCount = 2;</code>
     */
    public Builder setCallCount(int value) {
      bitField0_ |= 0x00000002;
      callCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 callCount = 2;</code>
     */
    public Builder clearCallCount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      callCount_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:dconcurrent.DStatus)
  }

  static {
    defaultInstance = new DStatus(true);
    defaultInstance.initFields();
  }

  // @@protoc_insertion_point(class_scope:dconcurrent.DStatus)
}

